query queryNavigationById($id: String!) {
    uiNavigation(id: $id) {
        internalName
        navigationItemsCollection {
            items {
                __typename
                ... on ContentBrand {
                    sys {
                        id
                    }
                    slug
                    title
                }
                ... on PageGeneric {
                    sys {
                        id
                    }
                    title
                    slug
                    internalName
                }
            }
        }
    }
}
