query queryBrands {
    contentBrandCollection {
        items {
            sys {
                id
            }
            title
           logo {
               url
           }
            description {
                json
            }
        }
    }
}
