query queryBrands {
    contentBrandCollection {
        items {
            sys {
                id
            }
            slug
            title
           logo {
               url
           }
            cardImage {
                url
            }
            description {
                json
            }
            logo {
                url
                title
            }
        }
    }
}
