query queryBrandBySlug($id: String!) {
    contentBrand(id: $id) {
        title
        description {
            json
        }
        logo {
            url
        }
        sectionsCollection {
            items {
                ...grid
            }
        }
    }
}
