query queryProjectById($id: String!) {
    contentProject(id: $id) {
        sys {
            id
        }
        name
        description {
            json
        }
        teaserImage {
            url
            title
            width
            height
        }
    }
}
